# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-15 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geo_lat', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('geo_long', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('requests', models.PositiveIntegerField(default=0)),
                ('bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('left_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('left_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('right_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('right_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
                ('top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hotspot.ClusterModel')),
            ],
        ),
        migrations.CreateModel(
            name='HotspotModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=12)),
                ('geo_long', models.DecimalField(decimal_places=6, max_digits=12)),
                ('category', models.PositiveIntegerField(choices=[(0, 'Unknown'), (1, 'Hotel'), (2, 'Food & Restaurant'), (3, 'Entertainment'), (4, 'Shop'), (5, 'Travel')], default=0)),
                ('desc', models.CharField(max_length=256, null=True)),
                ('image', models.URLField(max_length=256, null=True)),
                ('country', models.CharField(max_length=128, null=True)),
                ('city', models.CharField(max_length=64, null=True)),
                ('zip', models.CharField(max_length=32, null=True)),
                ('street', models.CharField(max_length=128, null=True)),
                ('phone', models.CharField(max_length=128, null=True)),
                ('url', models.URLField(max_length=256, null=True)),
                ('url_fb', models.URLField(max_length=256, null=True)),
                ('score', models.PositiveIntegerField(default=0)),
                ('plausibility', models.PositiveIntegerField(default=0)),
                ('updated', models.PositiveIntegerField(default=0)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hotspots', to='hotspot.ClusterModel')),
            ],
        ),
        migrations.CreateModel(
            name='HotspotScoreModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_type', models.PositiveIntegerField(default=0)),
                ('score', models.PositiveIntegerField(default=0)),
                ('score_weight', models.PositiveIntegerField(default=0)),
                ('spot', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotspot.HotspotModel')),
            ],
        ),
    ]
